restart.include.projectcommon=/build/classes/
restart.include.springcore=/spring-core-[\\w\\d-\\.]+\\.jar
restart.include.springwebflux=/spring-webflux-[\\w\\d-\\.]+\\.jar
restart.include.reactor=/reactor-[\\w\\d-\\.]+\\.jar
restart.include.netty=/netty-[\\w\\d-\\.]+\\.jar
