spring.application.name=demo
spring.ai.openai.api-key=sk-2a570f7ab9f544d4bdfea93df6530a51
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.chat.api-path=/v1/chat/completions
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.connection-timeout=30000
spring.ai.openai.read-timeout=30000
